#!/usr/bin/env python3
"""
merge_css.py

Scan HTML files for local stylesheet links, produce a merged CSS file preserving load order,
and optionally update HTML files to reference the merged file. Works in dry-run mode by default.

Limitations: This script uses simple text-based de-duplication and does not perform full CSS
parsing. It's intentionally conservative to avoid changing cascade semantics.
"""
from __future__ import annotations
import argparse
import os
import re
from pathlib import Path
from typing import List, Dict, Set, Tuple
from datetime import datetime

LINK_RE = re.compile(r"<link[^>]+rel=[\"']stylesheet[\"'][^>]*>", re.IGNORECASE)
HREF_RE = re.compile(r"href=[\"']([^\"']+)[\"']", re.IGNORECASE)


def find_html_files(root: Path) -> List[Path]:
    html_files: List[Path] = []
    for p in root.rglob("*.html"):
        html_files.append(p)
    return html_files


def extract_stylesheets_from_html(html_path: Path) -> List[str]:
    text = html_path.read_text(encoding="utf-8", errors="ignore")
    links = LINK_RE.findall(text)
    hrefs: List[str] = []
    for match in LINK_RE.finditer(text):
        tag = match.group(0)
        m = HREF_RE.search(tag)
        if m:
            hrefs.append(m.group(1))
    return hrefs


def is_remote(href: str) -> bool:
    href = href.strip()
    return href.startswith("http:") or href.startswith("https:") or href.startswith("//") or href.startswith("data:")


def resolve_css_path(html_file: Path, href: str) -> Path:
    # Resolve relative paths (../, ./) relative to the HTML file's directory.
    p = Path(href)
    if p.is_absolute():
        return p
    return (html_file.parent / href).resolve()


def read_css(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def dedupe_css_blocks(contents_list: List[Tuple[Path, str]]) -> str:
    """Naively merge CSS by keeping a seen set of lines and @import rules at top.
    This is conservative: it preserves order and avoids exact duplicates of lines.
    """
    imports: List[str] = []
    seen_lines: Set[str] = set()
    out_lines: List[str] = []

    for path, content in contents_list:
        lines = content.splitlines()
        for line in lines:
            s = line.strip()
            if not s:
                # keep single blank line for separation
                if out_lines and out_lines[-1].strip() != "":
                    out_lines.append("")
                continue
            if s.startswith("@import"):
                if s not in imports:
                    imports.append(s)
                continue
            # very conservative dedupe: exact line match
            if s not in seen_lines:
                seen_lines.add(s)
                out_lines.append(line)

    # produce combined content
    final: List[str] = []
    if imports:
        final.extend(imports)
        final.append("")
    final.extend(out_lines)
    final.append("")
    return "\n".join(final)


def detect_watermark(content: str) -> bool:
    """Detect likely watermark or vendor template markers in a CSS file.
    This uses a set of heuristics (keywords). It's not perfect; review results before deleting.
    """
    keys = [
        "watermark",
        "powered by",
        "template",
        "made by",
        "copyright",
        "all rights reserved",
        "author",
        "created by",
        "generated by",
        "theme",
    ]
    lower = content.lower()
    for k in keys:
        if k in lower:
            return True
    return False


def make_header(sources: List[Path], note: str = "") -> str:
    now = datetime.utcnow().isoformat(timespec='seconds') + 'Z'
    header = ["/* Merged CSS file", f"   Generated: {now}"]
    if note:
        header.append(f"   Note: {note}")
    header.append("   Source files:")
    for s in sources:
        header.append(f"     - {s}")
    header.append("*/")
    header.append("")
    return "\n".join(header)


def gather_css(root: Path) -> Tuple[List[Path], Dict[Path, List[Path]]]:
    html_files = find_html_files(root)
    css_order: List[Path] = []
    css_used_by: Dict[Path, List[Path]] = {}

    for html in html_files:
        hrefs = extract_stylesheets_from_html(html)
        for href in hrefs:
            if is_remote(href):
                continue
            css_path = resolve_css_path(html, href)
            if not css_path.exists():
                continue
            if css_path not in css_order:
                css_order.append(css_path)
            css_used_by.setdefault(css_path, []).append(html)

    return css_order, css_used_by


def update_html_references(html_paths: List[Path], merged_href: str, backup_ext: str = ".bak") -> None:
    for html in html_paths:
        txt = html.read_text(encoding="utf-8", errors="ignore")
        # Remove all link rel=stylesheet tags that reference local files
        def repl(m):
            tag = m.group(0)
            mhref = HREF_RE.search(tag)
            if not mhref:
                return tag
            href = mhref.group(1)
            if is_remote(href):
                return tag
            return ""

        newtxt = LINK_RE.sub(repl, txt)
        # Insert single merged link before closing </head> if present, otherwise at top
        link_tag = f'<link rel="stylesheet" href="{merged_href}">'
        if "</head>" in newtxt:
            newtxt = newtxt.replace("</head>", f"    {link_tag}\n</head>")
        else:
            newtxt = link_tag + "\n" + newtxt

        # backup and write
        bak = html.with_suffix(html.suffix + backup_ext)
        if not bak.exists():
            html.replace(html)  # touch to avoid race on Windows
            html.write_text(txt, encoding="utf-8")
            # write backup
            bak.write_text(txt, encoding="utf-8")
        html.write_text(newtxt, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Merge local CSS referenced by HTML files into a single stylesheet.")
    parser.add_argument("root", nargs="?", default=".", help="Workspace root to scan (default: current directory)")
    parser.add_argument("--output", "-o", default="assets/merged-styles.css", help="Merged CSS output path (relative to root)")
    parser.add_argument("--apply", action="store_true", help="Apply changes (write merged file and update HTML). Without this the script only does a dry-run")
    parser.add_argument("--delete-originals", action="store_true", help="If --apply is set, delete original CSS files after merging (use with caution)")
    parser.add_argument("--include-unreferenced", action="store_true", help="Also include CSS files not referenced by any HTML in the merge")
    parser.add_argument("--split-outputs", action="store_true", help="When including unreferenced, write them to a separate .unreferenced.css file")
    parser.add_argument("--show-unreferenced", action="store_true", help="Also show .css files not referenced by any HTML")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output_path = (root / args.output).resolve()

    css_order, css_used_by = gather_css(root)

    print(f"Found {len(css_order)} referenced local CSS files in HTML.")
    for i, p in enumerate(css_order, 1):
        print(f"  {i}. {p} (used by {len(css_used_by.get(p, []))} HTML files)")

    # read contents in order
    contents_list: List[Tuple[Path, str]] = []
    watermark_candidates: List[Path] = []
    for p in css_order:
        c = read_css(p)
        contents_list.append((p, c))
        if detect_watermark(c):
            watermark_candidates.append(p)

    # handle unreferenced inclusion if requested
    unreferenced_list: List[Tuple[Path, str]] = []
    if args.include_unreferenced:
        all_css = [p.resolve() for p in root.rglob("*.css")]
        for p in all_css:
            if p not in css_used_by and p not in css_order:
                c = read_css(p)
                unreferenced_list.append((p, c))
                if detect_watermark(c) and p not in watermark_candidates:
                    watermark_candidates.append(p)

    if watermark_candidates:
        print("\nWatermark/template-like candidates (review before deletion):")
        for p in watermark_candidates:
            print(f"  - {p}")

    merged = dedupe_css_blocks(contents_list)
    merged_unref = ""
    if unreferenced_list:
        merged_unref = dedupe_css_blocks(unreferenced_list)

    # list unreferenced CSS files if requested
    if args.show_unreferenced:
        all_css = [p.resolve() for p in root.rglob("*.css")]
        unreferenced = [p for p in all_css if p not in css_used_by]
        print(f"Found {len(unreferenced)} unreferenced .css files:")
        for p in unreferenced:
            print(f"  - {p}")

    if not args.apply:
        print("\nDry-run mode. No files were changed. Use --apply to write the merged CSS and update HTML.")
        print(f"Merged output would be written to: {output_path}")
        if merged_unref:
            out2 = output_path.with_name(output_path.name + ".unreferenced.css")
            print(f"Unreferenced merged output would be written to: {out2}")
        return

    # ensure output dir
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # write headers
    header_main = make_header([p for p, _ in contents_list], note="Merged referenced CSS files")
    output_path.write_text(header_main + "\n" + merged, encoding="utf-8")
    print(f"Wrote merged CSS to: {output_path}")

    if merged_unref:
        if args.split_outputs:
            out2 = output_path.with_name(output_path.name + ".unreferenced.css")
        else:
            out2 = output_path
        header_un = make_header([p for p, _ in unreferenced_list], note="Merged unreferenced CSS files")
        # if writing to same file, append with separator
        if out2 == output_path:
            with output_path.open("a", encoding="utf-8") as f:
                f.write("\n/* --- Unreferenced merged CSS --- */\n")
                f.write(header_un + "\n" + merged_unref)
            print(f"Appended unreferenced CSS to: {output_path}")
        else:
            out2.write_text(header_un + "\n" + merged_unref, encoding="utf-8")
            print(f"Wrote unreferenced merged CSS to: {out2}")

    # update HTML files that reference these CSS files
    affected_html: Set[Path] = set()
    for p, htmls in css_used_by.items():
        for h in htmls:
            affected_html.add(h)

    update_html_references(list(affected_html), os.path.relpath(output_path, root))
    print(f"Updated {len(affected_html)} HTML files to reference the merged stylesheet.")

    if args.delete_originals:
        for p in css_order:
            try:
                p.unlink()
                print(f"Deleted original CSS: {p}")
            except Exception as e:
                print(f"Failed to delete {p}: {e}")


if __name__ == "__main__":
    main()
